# Generated by Django 5.2.8 on 2025-12-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('API_Beneficiario', '0001_initial'),
        ('API_PDP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desplazamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esquema_extensivo', models.BooleanField(default=False)),
                ('tipo_esquema', models.CharField(choices=[('CORPORACIÓN Y/O ASOCIACIÓN', 'CORPORACIÓN Y/O ASOCIACIÓN'), ('ESQUEMA COLECTIVO', 'ESQUEMA COLECTIVO'), ('ESQUEMA INDIVIDUAL', 'ESQUEMA INDIVIDUAL')], default='ESQUEMA INDIVIDUAL', max_length=30)),
                ('nombre_corporacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nit_corporacion', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_corporacion', models.CharField(blank=True, max_length=15, null=True)),
                ('corporacion_poblacion_cerrem', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_representante', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula_representante', models.CharField(blank=True, max_length=20, null=True)),
                ('celular_representante', models.CharField(blank=True, max_length=15, null=True)),
                ('representante_poblacion_cerrem', models.CharField(blank=True, max_length=100, null=True)),
                ('requerimiento_terrestre', models.BooleanField(default=False)),
                ('requerimiento_aereo', models.BooleanField(default=False)),
                ('requerimiento_fluvial', models.BooleanField(default=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ciudad_origen', models.CharField(max_length=100)),
                ('ciudad_destino', models.CharField(max_length=100)),
                ('vuelo_data', models.JSONField(blank=True, null=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Beneficiario.beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='DesplazamientoPDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fija', 'Fija'), ('temporal', 'Temporal')], max_length=10)),
                ('desplazamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_Desplazamiento.desplazamiento')),
                ('pdp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API_PDP.pdp')),
            ],
        ),
        migrations.AddField(
            model_name='desplazamiento',
            name='pdps',
            field=models.ManyToManyField(blank=True, through='API_Desplazamiento.DesplazamientoPDP', to='API_PDP.pdp'),
        ),
    ]
